version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    # image: postgres:${POSTGRES_VERSION:-14}-alpine
    # environment:
    #   POSTGRES_DB: ${POSTGRES_DB:-app}
    #   # You should definitely change the password in production
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
    #   POSTGRES_USER: ${POSTGRES_USER:-app}
    # volumes:
    #   - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3307:3306
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    depends_on: 
      - database
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
